services:
  web:
    build: ./web
    ports:
      - "8000:5000"
    environment:
      - FILESERVER_HOST=internal-fileserver:8080
    networks:
      - nightshift_net
    depends_on:
      - ops-server

  ops-server:
    build: ./ops-server
    platform: linux/amd64
    hostname: internal-fileserver
    ports:
      - "2121:21"
      - "30000-30009:30000-30009"
    networks:
      nightshift_net:
        aliases:
          - internal-fileserver

networks:
  nightshift_net:
    driver: bridge